version: '3'
services:

  django:
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  tasks:
    volumes:
      - .:/code

  elm:
    volumes:
      - ./jarbas:/code/jarbas

  postgres:
    image: postgres:10.3-alpine
    volumes:
      - ./db:/var/lib/postgresql
    ports:
      - "5432:5432"
